apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: doc-intel
data:
  QDRANT_URL:    "http://qdrant-service:6333"
  RABBITMQ_URL:  "amqp://guest:guest@rabbitmq-service:5672/"
  DATABASE_URL:  "postgresql://postgres:postgres@postgres-service:5432/docs"
  WORKER_URL:    "http://worker-api-service:8000"
  GATEWAY_URL:   "http://gateway-service:3000"
  UPLOAD_DIR:    "/data/uploads"
